package demo;

import demo.person.Person;
import demo.person.PersonSearch;
import demo.person.PersonSearchImpl;
import java.awt.*;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends JFrame {
    
    private final List<Person> persons = Arrays.asList(
            new Person("Oleg", new Date(725587200000L)), //29 Dec 1992 00:00:00 GMT
            new Person("John", new Date(946684800000L)));//01 Jan 2000 00:00:00 GMT
    
    private final PersonSearch search = new PersonSearchImpl(persons);

    public MainFrame() {
        initComponents();//should be first. it is generated by NetBeans
        setPersonsDataToTable();
        addListenersForTextFieldsToSearchRows(nameTextField, dateTextField);
    }    
    
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }    
    
    private void setPersonsDataToTable() {
        DefaultTableModel model = (DefaultTableModel)personTable.getModel();
        model.addRow(new Object[]{persons.get(0).getName(), persons.get(0).getDateOfBirth()});
        model.addRow(new Object[]{persons.get(1).getName(), persons.get(1).getDateOfBirth()});
    }

    private void addListenersForTextFieldsToSearchRows(JTextField... fields) {
        for(JTextField field : fields) {
            field.getDocument().addDocumentListener(getListenerToSearch(field));
        }
    }
    
    private void searchPatientById(JTextField field) {
        int personId = field == dateTextField ? findByDate(field) : search.searchPerson(field.getText());
        if(personId != -1) selectRowAndColumn(personId);
    }

    private int findByDate(JTextField field) {
        Date personDate = DateFormatChecker.toDate(field.getText());
        return personDate != null ? search.searchPerson(personDate) : -1;
    }

    private void selectRowAndColumn(int personColumn) {
        personTable.changeSelection(personColumn, personColumn, false, false);
        personTable.setColumnSelectionInterval(0, 1);
    }
    
    private DocumentListener getListenerToSearch(JTextField field) {
        return new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                searchPatientById(field);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                //do nothing
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchPatientById(field);
            }
        };
    }

    private static final class DateFormatChecker {

        //required to make app independent to local machine time
        static {TimeZone.setDefault(TimeZone.getTimeZone("UTC"));}

        private static final SimpleDateFormat SIMPLE_DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");

        private static Date toDate(String date) {
            try {
                return SIMPLE_DATE_FORMAT.parse(date);
            } catch (ParseException e) {
                return null;
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPersonTable = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        nameTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        searchByNameLabel = new javax.swing.JLabel();
        searchByDateOfBirthLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelPersonTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Date of birth"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personTable.setColumnSelectionAllowed(true);
        personTable.getTableHeader().setReorderingAllowed(false);
        panelPersonTable.setViewportView(personTable);
        personTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (personTable.getColumnModel().getColumnCount() > 0) {
            personTable.getColumnModel().getColumn(0).setResizable(false);
            personTable.getColumnModel().getColumn(1).setResizable(false);
        }

        searchByNameLabel.setText("Search by name");

        searchByDateOfBirthLabel.setText("Search by date of birth");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPersonTable, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchByNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateTextField)
                    .addComponent(searchByDateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchByNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(searchByDateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPersonTable, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JScrollPane panelPersonTable;
    private javax.swing.JTable personTable;
    private javax.swing.JLabel searchByDateOfBirthLabel;
    private javax.swing.JLabel searchByNameLabel;
    // End of variables declaration//GEN-END:variables
}
